---
# tasks file for roles/createDB
- name: ansible create directory
  file:
    path: "{{ PROJECT_DIR }}"
    state: directory
    mode: "u=rwx,g=rx,o=rx"

- name: create terraform plan from template
  template:
    src: create_pg_DB.tf.j2
    dest: "{{ PROJECT_DIR }}/create_pg_DB.tf"
    owner: root
    group: root
    mode: 0644

- name: Apply Terraform Plan
  terraform:
    project_path: "{{ PROJECT_DIR }}"
    lock: no
    state: present
    force_init: true

